In [25]:
import pandas as pd
import numpy as np
import keras



In [125]:
df = pd.read_csv('Data1.csv')

df.drop(columns=['StudentID','First Name','Last Name'],inplace=True)

In [126]:
print(df.head(5))

   Gender Department  CGPA   HTML    CSS  JAVASCRIPT    PHP    SQL Company
0  Female         IT   6.3  False  False        True   True  False     cp5
1    Male         IT   9.0   True  False        True   True   True     cp9
2  Female        CSE   7.5   True   True       False   True   True     cp9
3    Male         IT   7.8  False   True       False  False  False     cp0
4  Female         EE   8.0   True  False        True  False   True     cp3


In [127]:
df['HTML']=df['HTML'].astype(int)
df['CSS']=df['CSS'].astype(int)
df['PHP']=df['PHP'].astype(int)
df['JAVASCRIPT']=df['JAVASCRIPT'].astype(int)
df['SQL']=df['SQL'].astype(int)

In [128]:
x=df.iloc[:, 0:8]
y=df.iloc[:, 8]

In [129]:
from sklearn import preprocessing
s1=preprocessing.LabelEncoder()
x.iloc[:, 0]= s1.fit_transform(x.iloc[:, 0])
s2=preprocessing.LabelEncoder()
x.iloc[:, 1]= s2.fit_transform(x.iloc[:, 1])

In [130]:
s3=preprocessing.LabelEncoder()
y= s3.fit_transform(y)

In [131]:
y = np.reshape(y, (-1, 1))
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
y=enc.fit_transform(y).toarray()


In [132]:

s1=preprocessing.LabelEncoder()
x.iloc[:, 0]= s1.fit_transform(x.iloc[:, 0])
enc = OneHotEncoder(categorical_features=[1])
x=enc.fit_transform(x).toarray()

In [61]:
import keras
from keras.models import Sequential
from keras.layers import Dense,Flatten,Dropout

In [133]:
 model = Sequential([
            Dense(48, input_shape=(11,), activation='relu'),
            Dense(48, activation='relu'),
            Dense(10, activation='sigmoid')
            ])

/home/abhiit98/.local/lib/python3.5/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=11, units=12, activation="relu")`
  """Entry point for launching an IPython kernel.
/home/abhiit98/.local/lib/python3.5/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=12, units=12, activation="relu")`
  
/home/abhiit98/.local/lib/python3.5/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=12, units=10, activation="sigmoid")`
  This is separate from the ipykernel package so we can avoid doing imports until


In [134]:
model.compile(loss='categorical_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

In [138]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2, random_state=40)

In [136]:
print(x_test.shape)


(109, 11)


In [139]:
model.fit(x_train, y_train, epochs=1000, batch_size=32)

Epoch 1/1000
436/436 [==============================] - 0s 33us/step - loss: 1.2375 - acc: 0.6216
Epoch 2/1000
436/436 [==============================] - 0s 39us/step - loss: 1.1972 - acc: 0.6284
Epoch 3/1000
436/436 [==============================] - 0s 36us/step - loss: 1.1653 - acc: 0.6353
Epoch 4/1000
436/436 [==============================] - 0s 42us/step - loss: 1.1580 - acc: 0.6239
Epoch 5/1000
436/436 [==============================] - 0s 34us/step - loss: 1.1440 - acc: 0.6307
Epoch 6/1000
436/436 [==============================] - 0s 40us/step - loss: 1.1342 - acc: 0.6353
Epoch 7/1000
436/436 [==============================] - 0s 34us/step - loss: 1.1130 - acc: 0.6307
Epoch 8/1000
436/436 [==============================] - 0s 44us/step - loss: 1.0971 - acc: 0.6399
Epoch 9/1000
436/436 [==============================] - 0s 34us/step - loss: 1.0992 - acc: 0.6445
Epoch 10/1000
436/436 [==============================] - 0s 42us/step - loss: 1.0989 - acc: 0.6353
Epoch 11/1000
436/4

In [116]:
y_pred=model.predict(x_test)
y_pred =(y_pred>=0.5)
y_pred = y_pred.astype(int)
print(y_pred)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [123]:
from sklearn.metrics import confusion_matrix

In [124]:
print(cn)

[[3 0 0 0 0 0 0 0 0 0]
 [7 3 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [4 0 0 0 0 0 0 0 0 0]
 [4 0 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0]
 [2 0 0 0 1 0 0 0 0 0]
 [4 0 0 0 0 0 0 0 0 0]
 [5 0 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0]]
